interface DraftViewerProps {
  subject: string
  body: string
  templateUsed?: string
  modelName?: string
}

export function DraftViewer({ subject, body, templateUsed, modelName }: DraftViewerProps) {
  const paragraphs = body.split('\n\n').map((p) => p.trim()).filter(Boolean)

  return (
    <div style={{
      border: '1px solid #e2e8f0',
      borderRadius: 8,
      overflow: 'hidden',
      backgroundColor: 'white',
      boxShadow: '0 1px 3px rgba(0, 0, 0, 0.08)',
    }}>
      {/* Subject header */}
      <div style={{
        padding: '14px 20px',
        borderBottom: '1px solid #e2e8f0',
        backgroundColor: '#f8fafc',
      }}>
        <div style={{ fontSize: 12, color: '#6b7280', marginBottom: 4, textTransform: 'uppercase', letterSpacing: 0.5 }}>
          Subject
        </div>
        <div style={{ fontSize: 15, fontWeight: 600, color: '#1e293b' }}>
          {subject}
        </div>
      </div>

      {/* Email body */}
      <div style={{ padding: '20px 24px' }}>
        {paragraphs.map((paragraph, i) => {
          // Handle list items (lines starting with -)
          const lines = paragraph.split('\n')
          const isList = lines.some((line) => line.trim().startsWith('- '))

          if (isList) {
            const listItems: string[] = []
            const preText: string[] = []

            for (const line of lines) {
              if (line.trim().startsWith('- ')) {
                listItems.push(line.trim().slice(2))
              } else {
                preText.push(line)
              }
            }

            return (
              <div key={i} style={{ marginBottom: 16 }}>
                {preText.length > 0 && (
                  <p style={{ fontSize: 14, lineHeight: 1.7, color: '#1e293b', marginBottom: 8 }}>
                    {preText.join('\n')}
                  </p>
                )}
                <ul style={{
                  margin: 0,
                  paddingLeft: 20,
                  display: 'flex',
                  flexDirection: 'column',
                  gap: 4,
                }}>
                  {listItems.map((item, j) => (
                    <li key={j} style={{ fontSize: 14, lineHeight: 1.7, color: '#1e293b' }}>
                      {item}
                    </li>
                  ))}
                </ul>
              </div>
            )
          }

          return (
            <p key={i} style={{
              fontSize: 14,
              lineHeight: 1.7,
              color: '#1e293b',
              marginBottom: 16,
              whiteSpace: 'pre-wrap',
            }}>
              {paragraph}
            </p>
          )
        })}
      </div>

      {/* Footer with template + model info */}
      {(templateUsed || modelName) && (
        <div style={{
          padding: '10px 20px',
          borderTop: '1px solid #e2e8f0',
          backgroundColor: '#f8fafc',
          display: 'flex',
          gap: 12,
          alignItems: 'center',
          flexWrap: 'wrap',
        }}>
          {templateUsed && (
            <span style={{
              display: 'inline-block',
              padding: '2px 8px',
              borderRadius: 4,
              fontSize: 12,
              fontWeight: 500,
              color: '#7c3aed',
              backgroundColor: '#ede9fe',
            }}>
              {templateUsed.replace(/_/g, ' ')}
            </span>
          )}
          {modelName && (
            <span style={{ fontSize: 12, color: '#9ca3af' }}>
              Generated by {modelName}
            </span>
          )}
        </div>
      )}
    </div>
  )
}
