"""V001 initial schema with all 10 tables

Revision ID: a7c1cdb3ce41
Revises: 
Create Date: 2026-04-01 19:26:12.395544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7c1cdb3ce41'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'seeding_knowledge', 'running', 'waiting_for_approval', 'partially_completed', 'completed', 'failed', 'cancelled', name='country_job_status'), nullable=False),
    sa.Column('agno_session_id', sa.String(length=200), nullable=True),
    sa.Column('agno_run_id', sa.String(length=200), nullable=True),
    sa.Column('current_stage', sa.String(length=100), nullable=True),
    sa.Column('summary_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('user_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prior_job_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('total_token_count', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_jobs_country'), 'country_jobs', ['country'], unique=False)
    op.create_table('country_knowledge',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('knowledge_type', sa.Enum('directory', 'registry', 'search_strategy', 'locale', 'learning', name='knowledge_type'), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_knowledge_country'), 'country_knowledge', ['country'], unique=False)
    op.create_index('ix_knowledge_country_type', 'country_knowledge', ['country', 'knowledge_type'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country_job_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('role_title', sa.String(length=300), nullable=True),
    sa.Column('whatsapp', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=300), nullable=True),
    sa.Column('company_name', sa.String(length=300), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('source_urls', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.Enum('discovered', 'normalized', 'verified', 'needs_review', 'rejected', name='lead_verification_status'), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('confidence_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('discovery_skill_used', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_job_id'], ['country_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index('ix_leads_job_confidence', 'leads', ['country_job_id', sa.literal_column('confidence_score DESC')], unique=False)
    op.create_table('skill_invocation_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country_job_id', sa.UUID(), nullable=False),
    sa.Column('skill_name', sa.String(length=200), nullable=False),
    sa.Column('skill_version', sa.String(length=50), nullable=True),
    sa.Column('agent_name', sa.String(length=200), nullable=True),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_job_id'], ['country_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_invocation_logs_country_job_id'), 'skill_invocation_logs', ['country_job_id'], unique=False)
    op.create_table('workflow_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country_job_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skill_invoked', sa.String(length=200), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_job_id'], ['country_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_events_country_job_id'), 'workflow_events', ['country_job_id'], unique=False)
    op.create_table('email_drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('country_job_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'draft_generated', 'pending_review', 'changes_requested', 'draft_regenerating', 'draft_regenerated', 'approved', 'sending', 'sent', 'rejected', 'send_failed', name='outreach_status'), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=True),
    sa.Column('template_used', sa.String(length=200), nullable=True),
    sa.Column('skill_used', sa.String(length=200), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_system', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['country_job_id'], ['country_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_drafts_lead_version', 'email_drafts', ['lead_id', 'version_number'], unique=False)
    op.create_index(op.f('ix_email_drafts_lead_id'), 'email_drafts', ['lead_id'], unique=False)
    op.create_table('lead_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_title', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.String(length=100), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_sources_lead_id'), 'lead_sources', ['lead_id'], unique=False)
    op.create_table('verification_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('discovered', 'normalized', 'verified', 'needs_review', 'rejected', name='lead_verification_status'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('dimension', sa.Enum('entity', 'contact', 'source_quality', 'dedup', name='verification_dimension'), nullable=False),
    sa.Column('verifier_notes', sa.Text(), nullable=True),
    sa.Column('contradictions_found', sa.Text(), nullable=True),
    sa.Column('duplicate_of_lead_id', sa.UUID(), nullable=True),
    sa.Column('skill_used', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of_lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_records_lead_id'), 'verification_records', ['lead_id'], unique=False)
    op.create_table('draft_review_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_draft_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.String(length=200), nullable=False),
    sa.Column('action', sa.Enum('approve', 'request_changes', 'reject', name='review_action'), nullable=False),
    sa.Column('structured_feedback_categories', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_draft_id'], ['email_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_review_actions_email_draft_id'), 'draft_review_actions', ['email_draft_id'], unique=False)
    op.create_table('email_send_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_draft_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('send_method', sa.String(length=50), nullable=True),
    sa.Column('provider_message_id', sa.String(length=500), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('send_status', sa.String(length=50), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['email_draft_id'], ['email_drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_send_logs_email_draft_id'), 'email_send_logs', ['email_draft_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_send_logs_email_draft_id'), table_name='email_send_logs')
    op.drop_table('email_send_logs')
    op.drop_index(op.f('ix_draft_review_actions_email_draft_id'), table_name='draft_review_actions')
    op.drop_table('draft_review_actions')
    op.drop_index(op.f('ix_verification_records_lead_id'), table_name='verification_records')
    op.drop_table('verification_records')
    op.drop_index(op.f('ix_lead_sources_lead_id'), table_name='lead_sources')
    op.drop_table('lead_sources')
    op.drop_index(op.f('ix_email_drafts_lead_id'), table_name='email_drafts')
    op.drop_index('ix_drafts_lead_version', table_name='email_drafts')
    op.drop_table('email_drafts')
    op.drop_index(op.f('ix_workflow_events_country_job_id'), table_name='workflow_events')
    op.drop_table('workflow_events')
    op.drop_index(op.f('ix_skill_invocation_logs_country_job_id'), table_name='skill_invocation_logs')
    op.drop_table('skill_invocation_logs')
    op.drop_index('ix_leads_job_confidence', table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_table('leads')
    op.drop_index('ix_knowledge_country_type', table_name='country_knowledge')
    op.drop_index(op.f('ix_country_knowledge_country'), table_name='country_knowledge')
    op.drop_table('country_knowledge')
    op.drop_index(op.f('ix_country_jobs_country'), table_name='country_jobs')
    op.drop_table('country_jobs')
    # ### end Alembic commands ###
