/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as LeadsIndexRouteImport } from './routes/leads/index'
import { Route as ApprovalsIndexRouteImport } from './routes/approvals/index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions/$sessionId'
import { Route as LeadsLeadIdRouteImport } from './routes/leads/$leadId'
import { Route as CountryNewRouteImport } from './routes/country/new'
import { Route as ApprovalsDraftIdRouteImport } from './routes/approvals/$draftId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsIndexRoute = ApprovalsIndexRouteImport.update({
  id: '/approvals/',
  path: '/approvals/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsLeadIdRoute = LeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryNewRoute = CountryNewRouteImport.update({
  id: '/country/new',
  path: '/country/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsDraftIdRoute = ApprovalsDraftIdRouteImport.update({
  id: '/approvals/$draftId',
  path: '/approvals/$draftId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals/$draftId': typeof ApprovalsDraftIdRoute
  '/country/new': typeof CountryNewRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/approvals/': typeof ApprovalsIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals/$draftId': typeof ApprovalsDraftIdRoute
  '/country/new': typeof CountryNewRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/approvals': typeof ApprovalsIndexRoute
  '/leads': typeof LeadsIndexRoute
  '/sessions': typeof SessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals/$draftId': typeof ApprovalsDraftIdRoute
  '/country/new': typeof CountryNewRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/approvals/': typeof ApprovalsIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals/$draftId'
    | '/country/new'
    | '/leads/$leadId'
    | '/sessions/$sessionId'
    | '/approvals/'
    | '/leads/'
    | '/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals/$draftId'
    | '/country/new'
    | '/leads/$leadId'
    | '/sessions/$sessionId'
    | '/approvals'
    | '/leads'
    | '/sessions'
  id:
    | '__root__'
    | '/'
    | '/approvals/$draftId'
    | '/country/new'
    | '/leads/$leadId'
    | '/sessions/$sessionId'
    | '/approvals/'
    | '/leads/'
    | '/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsDraftIdRoute: typeof ApprovalsDraftIdRoute
  CountryNewRoute: typeof CountryNewRoute
  LeadsLeadIdRoute: typeof LeadsLeadIdRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  ApprovalsIndexRoute: typeof ApprovalsIndexRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/': {
      id: '/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals/': {
      id: '/approvals/'
      path: '/approvals'
      fullPath: '/approvals/'
      preLoaderRoute: typeof ApprovalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$leadId': {
      id: '/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof LeadsLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/country/new': {
      id: '/country/new'
      path: '/country/new'
      fullPath: '/country/new'
      preLoaderRoute: typeof CountryNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals/$draftId': {
      id: '/approvals/$draftId'
      path: '/approvals/$draftId'
      fullPath: '/approvals/$draftId'
      preLoaderRoute: typeof ApprovalsDraftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsDraftIdRoute: ApprovalsDraftIdRoute,
  CountryNewRoute: CountryNewRoute,
  LeadsLeadIdRoute: LeadsLeadIdRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  ApprovalsIndexRoute: ApprovalsIndexRoute,
  LeadsIndexRoute: LeadsIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
